name: Math counter
on: workflow_dispatch
permissions:
  contents: write
env:
  APP_NAME: MathCounter 
  APP_VERSION: v.1.0.2
  KEYWORD: lol
jobs:
  math_counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          echo "Your app name is $APP_NAME and version is $APP_VERSION"
          printf "$KEYWORD: Push implemented\n" >> log.txt
          COUNT=$(cat counter.txt)
          COUNT=$((COUNT+1))
          echo "$COUNT" > counter.txt
          git config --global user.name 'veetipyoria'
          git config --global user.email 'vpyoria24@students.oamk.fi'
          git add .
          git commit -m 'New push info'

    
