name: harjoitus
on:
  issues:
    types: opened
  workflow_dispatch:
  
jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: file creation
        run: |
          touch info.txt
          echo "jotain" > info.txt
      - name: backup
        run: |
          mkdir backup
          cp info.txt backup/info.txt
      - name: contents
        run: |
          ls -la
          ls -la backup
          cat info.txt

  yesno:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://yesno.wtf/api
